In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([11,22,33])
c=np.array([44,55,66])
x1 = np.concatenate((a,b,c),axis=0)  # 默认情况下，axis=0可以不写
#array([ 1,  2,  3, 11, 22, 33, 44, 55, 66]) #对于一维数组拼接，axis的值不影响最后的结果

print(x1.shape)
 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,21,31],[7,8,9]])
x2 = np.concatenate((a,b),axis=0)
print(a.shape)
#array([[ 1,  2,  3],
       #[ 4,  5,  6],
       #[11, 21, 31],
       #[ 7,  8,  9]])

print(x2.shape)       
 
x3 = np.concatenate((a,b),axis=1)  #axis=1表示对应行的数组进行拼接
#array([[ 1,  2,  3, 11, 21, 31],
       #[ 4,  5,  6,  7,  8,  9]])

print(x3.shape)

(9,)
(2, 3)
(4, 3)
(2, 6)
