In [2]:
import numpy
numpy.__version__

'1.23.1'

In [14]:
import numpy as np
np.random.seed(0)
'''
x1 = np.arange(10)
print(x1)

#x[start:stop:step] slicing the array given
print(x1[:5]) #print  first five values
y = x1[0:9:2]
print(x1[::2]) #print any other values
print(y)
'''

#x1 = np.arange(1, 10).reshape(3,3) #change the shape of the array to a 3*3 matrix
#print(x1)
x2 = np.arange(1,10)
print(x2)
x2 = x2[np.newaxis, :]
print(x2)

x3 = [1, 2, 3] #make two arrays together
x4 = [3, 2, 1]
y = np.concatenate([x3, x4])
print(y)

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 3 2 1]


In [15]:
x = np.arange(10)
y = np.add(x, 5)
print(y)

[ 5  6  7  8  9 10 11 12 13 14]


In [1]:
import numpy as np
a = np.array([0, 1, 2])
b = np.ones((3, 3))
#print(a + b)  #broadcasting广播，a只有一行三列，所以a复制三次来和b一样大小从而实现相加

#print(a + 5)

x = np.arange(3)[np.newaxis, :, np.newaxis]
print(x.shape)
#print(x[1])
print(x)

(1, 3, 1)
[[[0]
  [1]
  [2]]]


All training data are split to three parts: Train, Test and Validation. 
